image muiquiet = "images/muiquiet.png"
image muitalking = "images/muitalking.png"
image yuichiro = "images/yuichiro.png"
image bg forest_sunset ="images/forest_sunset.png"
image bg forest_night = "images/forest_night.png"